# Basic
title: 陈锦龙
subtitle: 人总是四处逃避，却永远无法回避自己
welcome_message:男，摩羯座一枚
description: 
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: 我的博客

# Navigation buttons in the front page.
nav:
    - {title: github, description: 源码, url: 'https://github.com/SnowyLChen/SnowyLChen.github.io'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: onevcat
    github: SnowLChen
    twitter: onevcat
    gplus: 107108267983477358170
    mail: 15293616670@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
